/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.bishoybasily.java-conventions")
}

dependencies {
    api(project(":springframework-commons-core"))
    implementation("org.springframework.amqp:spring-rabbit:2.2.11.RELEASE")
}

description = "springframework-commons-amqp"
