/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.bishoybasily.java-conventions")
}

dependencies {
    implementation("org.springframework:spring-core:5.3.4")
    implementation("org.springframework.data:spring-data-commons:2.2.11.RELEASE")
    api("com.fasterxml.jackson.core:jackson-core:2.12.5")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.5")
}

description = "springframework-commons :: core"
