/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "springframework-commons"
include(":springframework-commons-core")
include(":springframework-commons-jpa")
include(":springframework-commons-amqp")
