name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.gpg_private_key }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}
        run: |
          mvn \
            -D gpg.keyname=ED3F24F6A3AA99BA \
            -D gpg.passphrase=${{ secrets.gpg_passphrase }} \
            clean deploy
